### ISSUE TITLE
Resolution over 1024 seems to not generate properly.

### ISSUE THREAD

**Issue by warvstar** [Forceflow/cuda_voxelizer#10]
This is a 1024 res voxel model and looks correct
https://imgur.com/p0Wg37l

This is at 2048, it appears to wrap around... should be a simple fix.
https://imgur.com/sBzhsmW

**Comment by Forceflow** [comment]
Interesting. Marking as bug.

**Comment by warvstar** [comment]
Yes exporting to binvox, I'm fairly sure I checked with viewvox and my own opengl renderer. I'll have to double-check this in a couple weeks when I'm not away from my desk. I can post some code at that point to, for my importer.

**Comment by Forceflow** [comment]
I'm starting to think this is a binvox limitation. I'm writing an exporter to . obj (point cloud) soon, so we can verify.

**Comment by Forceflow** [comment]
Nope, it was me. Of course, somewhere an int32 overflowed - fixed in 70700c9ff4af71e5980837350ffd4b499df0c4c6

**Comment by warvstar** [comment]
> Nope, it was me. Of course, somewhere an int32 overflowed - fixed in [70700c9](https://github.com/Forceflow/cuda_voxelizer/commit/70700c9ff4af71e5980837350ffd4b499df0c4c6)
> 
> I tested it on a 2048x2048x2048 export to obj.

I figured it was an overflow but couldn't find it, nice to see it's fixed!

**Comment by Forceflow** [comment]
> 
> 
> > Nope, it was me. Of course, somewhere an int32 overflowed - fixed in [70700c9](https://github.com/Forceflow/cuda_voxelizer/commit/70700c9ff4af71e5980837350ffd4b499df0c4c6)
> > I tested it on a 2048x2048x2048 export to obj.
> 
> I figured it was an overflow but couldn't find it, nice to see it's fixed!

I did an explicit static cast to 64-bit integers on two locations where I thought it could become problematic for large values, and that seems to have fixed it.

**Comment by Forceflow** [comment]
Anyway, thanks for reporting @warvstar, closing for now!
