### ISSUE TITLE
Program cannot be launched on Windows: cudart64_102.dll is missing

### ISSUE THREAD

**Issue by claell** [Forceflow/cuda_voxelizer#21]
I just tried the Windows version from this release. Unfortunately it does not seem to work and gives the following error. Is there anythin needed in addition to make it work?

Also it seems like the DLLs contained in the release zip are cudart64_90.dll, so maybe they need an update?

**Comment by Forceflow** [comment]
Holy guacamole, indeed, those are the default CUDA 9.x dll's that are still bundled. I never noticed, because I think the newer ones are in my system path. Rebuilding!

**Comment by Forceflow** [comment]
Fixed with release https://github.com/Forceflow/cuda_voxelizer/releases/tag/v0.4.4b

**Comment by claell** [comment]
Thanks for the quick fix! Unfortunately now the program complains about MSVCP140D.dll missing.

**Comment by Forceflow** [comment]
> 
> 
> Thanks for the quick fix! Unfortunately now the program complains about MSVCP140D.dll missing.

Are you running the debugging version? Try the regular cuda_voxelizer.exe

**Comment by claell** [comment]
I did use the regular version. Happens with both apparently, just tried again.

**Comment by Forceflow** [comment]
It's a dependency on the VS Runtime Distributable. You can probably fix it by installing it from here: [64-bit VC Redist](https://aka.ms/vs/16/release/vc_redist.x64.exe)

**Comment by claell** [comment]
Ok. I also saw that when searching for the problem. I hoped it could be fixed by directly including the dll like the cuda ones, but that might not be possible to do apparently. Since I don't have admin rights on the PC, I will talk to my admin to install it and report afterwards, whether it helped.

**Comment by claell** [comment]
Unfortunately it did not help to install the Runtime Distributable. I think the needed debug dll is not included there, that is what a comment on Stackoverflow says: https://stackoverflow.com/questions/51437963/msvcp140d-dll-missing-is-there-a-way-around#comment89846081_51438014. What might help is to compile the program in an appropriate way without relying on debug dlls, see https://stackoverflow.com/a/51438071/3553923

Also for reference another project that had this issue: https://github.com/cirquit/trdrop/issues/14

Since this has become a larger issue, I created #23.

**Comment by Forceflow** [comment]
Right I'm going to mark this issue as fixed then, since the original cudart.dll thing was fixed.

Will look into that other DLL tomorrow.
