### ISSUE TITLE
Official Linux releases

### ISSUE THREAD

**Issue by claell** [Forceflow/cuda_voxelizer#22]
Currently it looks like one has to build for Linux manually. Unfortuantely I am not experienced in that and also there is not much documentation here about how to do that. I suspect it requires some pre setup of dependencies and is not just a simple command?

Thus it would be helpful having a Linux release available for download.

**Comment by Forceflow** [comment]
Since there is Cmake support, it's a matter of getting all the required dependencies installed on a system.
I've recently enabled automatic builds on Ubuntu, on the Travis CI service.

Have a look a the [travis.yml page](https://github.com/Forceflow/cuda_voxelizer/blob/master/.travis.yml) for an overview on what is needed to build on linux. Technically, just using the commands one by one will result in a succesfull build.

It's basicly the following steps:

- get CUDA installed
- get GLM, from the default repositories
- get the dependencies for trimesh2, from the default repositories
- clone my git repo for trimesh2 and build it using make
- run cmake on the cuda_voxelizer project
- run make

```
# Get CUDA (based on https://github.com/jeremad/cuda-travis)
  - INSTALLER=cuda-repo-${UBUNTU_VERSION}_${CUDA}_amd64.deb
  - wget http://developer.download.nvidia.com/compute/cuda/repos/${UBUNTU_VERSION}/x86_64/${INSTALLER}
  - sudo dpkg -i ${INSTALLER}
  - wget https://developer.download.nvidia.com/compute/cuda/repos/${UBUNTU_VERSION}/x86_64/7fa2af80.pub
  - sudo apt-key add 7fa2af80.pub
  - sudo apt update -qq
  - sudo apt install -y cuda-core-${CUDA_SHORT/./-} cuda-cudart-dev-${CUDA_SHORT/./-} cuda-cufft-dev-${CUDA_SHORT/./-}
  - sudo apt clean
  - CUDA_HOME=/usr/local/cuda-${CUDA_SHORT}
  - LD_LIBRARY_PATH=${CUDA_HOME}/lib64:${LD_LIBRARY_PATH}
  - PATH=${CUDA_HOME}/bin:${PATH}
  - PATH=${PATH}:${PWD}
# GLM: We can get this from the standard Ubuntu repository, any recent version will do
  - sudo apt-get install -y libglm-dev
# TRIMESH: Get dependencies from standard repos, and build project from git using makefile
  - sudo apt-get install -y mesa-common-dev libglu1-mesa-dev libxi-dev
  - git clone https://github.com/Forceflow/trimesh2.git
  - cd trimesh2 && make && cd ..

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
# Force CPU voxelization to test on Travis (we won't have a GPU here)
  - ./cuda_voxelizer -f ../test_models/bunny.OBJ -cpu
```

**Comment by Forceflow** [comment]
As for official Linux builds: I don't really see the point in doing that at the moment, since it's such a moving target. I'll maybe see if I can let the Travis build system place its files somewhere, I guess?

**Comment by claell** [comment]
Thanks for the detailed description! I saw the Travis integration, but did not have a closer look. I will try this commands now!

Regarding official builds: It is indeed a problem to cope with the variety of different Linux distributions. One approach might be to distribute as an AppImage, as that is meant to deal with such problems.

For most users however (probably including me) having the Travis build files available somewhere will already be pretty much sufficient.

**Comment by claell** [comment]
Just had some short try to make cuda_voxelizer on a kaggle VM. Unfortunately the code did not work out of the box and seems to need many manual adjustments, probably because the kaggle vm is a bit different than expected.

So I think I will use the Windows version for now and maybe try when there might be an "official" Linux build from Travis.

**Comment by Forceflow** [comment]
There is a cmake file that should generate a working Linux version right now. Closing this issue.
