### ISSUE TITLE
Program cannot be launched on Windows MSVCP140D.dll missing

### ISSUE THREAD

**Issue by claell** [Forceflow/cuda_voxelizer#23]
Since this seems to be a harder issue, I am creating a seperate one for this. The conversation from #21 can be moved here if that is possible.

**Comment by Forceflow** [comment]
Somewhere in the compilation process (maybe in trimesh2?) a VS debug DLL is added as a dependency. Will look into this.

Can you run the trimesh2 binaries without running into the same error? https://github.com/Forceflow/trimesh2/releases

**Comment by Forceflow** [comment]
> 
> 
> Thanks for having a closer look.
> 
> I just tested the trimesh2 binaries, you linked. I executed all binaries in `trimesh2\utils\win64` from the latest release without arguments from the command line. All binaries worked without any complain and printed the usage options on the command line.

Thanks, then I know the problem is in the cuda_voxelizer build process. Looking further into it this weekend.

**Comment by Forceflow** [comment]
I _think_ I fixed it by juggling some build parameters. Can you try the _cuda_voxelizer.exe_ in this archive?
[cuda_voxelizer_v0.4.4c.zip](https://github.com/Forceflow/cuda_voxelizer/files/4079793/cuda_voxelizer_v0.4.4c.zip)

**Comment by claell** [comment]
Works for me now (also did some quick testing of the voxelization; the CPU fallback mode seems to work fine), so I am closing this. Thanks for fixing!
