### ISSUE TITLE
Missing include directory in CMakeLists.txt

### ISSUE THREAD

**Issue by haehnpt** [Forceflow/cuda_voxelizer#26]
**CMakeList.txt** only specifies 

``
INCLUDE_DIRECTORIES(${Trimesh2_INCLUDE_DIR})
``

but it should be

``
INCLUDE_DIRECTORIES(${Trimesh2_INCLUDE_DIR} ${GLM_INCLUDE_DIR})
``

if I am not mistaken.

**Comment by Forceflow** [comment]
Which line are you referring to? The project currently builds on Travis CI using the current cmakefile.
Doesn't it on your system?

**Comment by YuliangXiu** [comment]
> **CMakeList.txt** only specifies
> 
> `INCLUDE_DIRECTORIES(${Trimesh2_INCLUDE_DIR})`
> 
> but it should be
> 
> `INCLUDE_DIRECTORIES(${Trimesh2_INCLUDE_DIR} ${GLM_INCLUDE_DIR})`
> 
> if I am not mistaken.
> 
> Edit: **Reading the readme helps**

Thanks for your advice! Just deleting `glm` in [cmakelist:82](https://github.com/Forceflow/cuda_voxelizer/blob/main/CMakeLists.txt#L82) solves my compile bug under Ubuntu.
