### ISSUE TITLE
Linux compatibility

### ISSUE THREAD

**Issue by aminm2a** [Forceflow/cuda_voxelizer#3]
Hi, 

Greate code, I'm trying to compile the code in linux but I'm having a wrong voxel grid (doesn't look ok) than the one in windows? any idea about the difference ?

Thanks

**Comment by Forceflow** [comment]
Hmm, there shouldn't be any linux-specific code in there that changes the voxel grid in any way. Are you visualizing using viewvox?

**Comment by aminm2a** [comment]
The code runs well on windows, but the problem occurs in Linux. But I finally figured out the problem, the code misses initializing the voxel table in CUDA memory to zeros. Doing this solves the problem.

**Comment by Forceflow** [comment]
And is the voxel grid distorted / flipped / mirrored, or just plain garbage? Tried with a different model?

**Comment by aminm2a** [comment]
Hi, initializing the voxel table to zeros in cuda memory solves the problem

**Comment by Forceflow** [comment]
Going to mark this as old/worksforme, since this is probably a side-effect of an old cuda version / not using managed memory.

Allocation has changed since 2016, and I cannot replicate this bug.
