### ISSUE TITLE
Windows error

### ISSUE THREAD

**Issue by PlayerUsr** [Forceflow/cuda_voxelizer#4]
Hi,

![capture](https://cloud.githubusercontent.com/assets/25033063/25860757/dd30704a-34e2-11e7-881b-10a19fda1a50.PNG)

Could you please help me ?

My OS is Windows 10 & i'm using VS 15.

thnx.

**Comment by Forceflow** [comment]
You have not changed the BINARY_OUTPUT_DIR variable - it copies the files to that directory when finished.
You can either edit the BINARY_OUTPUT_DIR variable in the .props file, or just ignore this error. Your built files will be in the default location.

**Comment by PlayerUsr** [comment]
Thank you very much for your answer !
I have not found how to change the BINARY_OUTPUT_DIR variable I'm usin VS 15.

Thank you in advance.

**Comment by Forceflow** [comment]
Check this MS help file: https://msdn.microsoft.com/en-us/library/ee479070(v=winembedded.60).aspx

**Comment by PlayerUsr** [comment]
resolved
thank you very much.

**Comment by Forceflow** [comment]
Hurray, np.
