### ISSUE TITLE
Can grid size of voxel  be different ?

### ISSUE THREAD

**Issue by sunjc0306** [Forceflow/cuda_voxelizer#54]
Thanks for your contribution !
I have a question.Can grid size of voxel  be different ? For example 128*192*128, rather than128*128*128 ?

**Comment by Forceflow** [comment]
I've been thinking about this - I think there's nothing in the original paper implementation that prohibits that, and I'm already splitting the sizes into X/Y/Z where I can, instead of using a singular gridsize value.

Feel free to experiment - changes should be relatively straightforward.
