### ISSUE TITLE
Is it a bug in src/main.cpp ?

### ISSUE THREAD

**Issue by ndroi** [Forceflow/cuda_voxelizer#59]
`size_t vtable_size = static_cast<size_t>(ceil(static_cast<size_t>(voxelization_info.gridsize.x) * static_cast<size_t>(voxelization_info.gridsize.y) * static_cast<size_t>(voxelization_info.gridsize.z)) / 8.0f)`

Should we ceil it after '/ 8.0f' ?

**Comment by Forceflow** [comment]
Yeah, I kind of implicitly expect the grid size to be a power of 2. 

But yes, in order to avoid invalid memory writes in case the model fills the last byte, a ceil() would definitely be safest here

**Comment by ndroi** [comment]
Thanks for answering me. 
I found another bug when `gridsize.x`, `gridsize.y` and `gridsize.z` unequal .
About the loaction expr, `size_t location = x + (y*gridsize.y) + (z*gridsize.y*gridsize.z);`,
I guess it should be `size_t location = x + (y*gridsize.x) + (z*gridsize.x*gridsize.y);`

**Comment by ndroi** [comment]
I will make a pull request.

**Comment by Forceflow** [comment]
Merged in e778b122a42f06a320fd353e337acb7002ac4dea

Thanks! Will be included in next non-dev release.
