### ISSUE TITLE
Issues in Setting up Cuda Voxelizer

### ISSUE THREAD

**Issue by SajanaW** [Forceflow/cuda_voxelizer#6]
Hi, 
I've been running into a lot of trouble setting up the repo and it's probably because I'm extremely new to the art of supporting C++ dependencies. 
My rig right now: 
 Windows 10  win64, Visual Studio v141, and the CUDA 9.2 toolset

I also downloaded the prebuilt libraries of trimesh2 (your [version](https://github.com/Forceflow/trimesh2)) and added libWin64v141 to src. I also got the 'release' version not the debug version.
I also downloaded Trimesh2 repo and added the header files to src.
I also got glm and added the glm folder in include to src.

As of now when I try to build the binaries on Visual Studio, I get the following link error:
unrecognized flag 'Ot'  not in 'p2'.
Based on my debugging it seems that this is because trimesh was compiled differently from my cuda_voxelizer solution build. But I am sure my build is Release, 64 and v141, the same as Trimesh.
Any help is much appreciated.

**Comment by Forceflow** [comment]
Try to compile Trimesh2 yourself, using the repo you cited.
