### ISSUE TITLE
FR: MagicaVoxel .vox / Minecraft .schematic format

### ISSUE THREAD

**Issue by thebigsmileXD** [Forceflow/cuda_voxelizer#63]
Would be nice to have this as an option for export

**Comment by thebigsmileXD** [comment]
Hmm, .schematic would also rock

**Comment by Forceflow** [comment]
Yeah, I'm looking at the following exporters:

https://github.com/aiekick/MagicaVoxel_File_Writer
https://github.com/jpaver/opengametools/blob/master/src/ogt_vox.h
https://github.com/Zarbuz/FileToVox

If you got any other libraries worth checking out, let me know.

**Comment by thebigsmileXD** [comment]
Original docs: https://github.com/ephtracy/voxel-model/blob/master/MagicaVoxel-file-format-vox.txt, Here is some well documented comment that shows some missing structures https://github.com/ephtracy/voxel-model/issues/19#issuecomment-392849751 and https://github.com/alexhunsley/numpy-vox-io maybe, it is sadly outdated though because the author has not updated the format yet. Over the last days i stumbled upon quite much of the .vox code, so much that i can barely see it anymore 😅

**Comment by Forceflow** [comment]
Implemented in the latest release. Thanks for bringing this to my attention. Will add more functionality (color sampling, gradients) in the future.
