### ISSUE TITLE
What the does the `TopLeftEdge` mean

### ISSUE THREAD

**Issue by maidamai0** [Forceflow/cuda_voxelizer#68]
Hi, thanks for sharing this code and I'm experimenting the code.
I don't quite understand the `TopLeftEdge` function
https://github.com/Forceflow/cuda_voxelizer/blob/8ad08043b1af5b9c6f3399322505e2faee83a28b/src/voxelize_solid.cu#L67

* Is this check necessary?
* What does it mean in geometry, does it mean the top left edge of a triange as the name implies, if yes why we should do this check?

**Comment by Forceflow** [comment]
Check the original Schwarz & Seidel paper this method is based on for details: http://research.michael-schwarz.com/publ/files/vox-siga10.pdf
