### ISSUE TITLE
do not work with 3060 rtx. Should it?

### ISSUE THREAD

**Issue by hitrpr** [Forceflow/cuda_voxelizer#71]
here is an error
cpu mode works
![изображение](https://user-images.githubusercontent.com/21099918/192906533-f87abea9-7502-47e2-881e-055786a51a6c.png)

**Comment by Forceflow** [comment]
Probably a compilation issue on my end. I'll check!

**Comment by Forceflow** [comment]
Try the new release: https://github.com/Forceflow/cuda_voxelizer/releases/tag/v0.5.1

**Comment by hitrpr** [comment]
> Try the new release: https://github.com/Forceflow/cuda_voxelizer/releases/tag/v0.5.1

Yes, thanks, now works with my GPU

**Comment by Forceflow** [comment]
Hurray!
