### ISSUE TITLE
Solid Voxels

### ISSUE THREAD

**Issue by csverma610** [Forceflow/cuda_voxelizer#8]
Hello,

I was wondering if your software can generate solid voxels. I noticed that with
the example, I get only the surface voxels.

Regards.

**Comment by Forceflow** [comment]
This software is built for surface voxelization. If your models are watertight, you can implement a fill pass yourself. Loop over the model once in every direction (X, Y, Z) and mark voxels as "filled" when you encountered at least one filled voxel, until you encounter the next voxel. This is called inside/outside filling. It's not perfect, and has edge cases, but might be enough for your case.

**Comment by claell** [comment]
I should have read that before. Any hope, solid voxelization will get added as an option?
