### ISSUE TITLE
trimesh2/include/Color.h(165):  error: more than one instance of overloaded function "cbrt" matches the argument list:

### ISSUE THREAD

**Issue by gjgjgjfff** [Forceflow/cuda_voxelizer#80]
An error occurs when I run cmake --build. --parallel 8
Can you help me figure out what the problem is？

Color.h(165):
static inline float cielab_nonlinearity(float x)
{
using namespace ::std;

if (x > 216.0f / 24389.0f)
	return cbrt(x);
else
	return 4.0f / 29.0f + (841.0f / 108.0f) * x;
}

**Comment by Forceflow** [comment]
Don't make duplicate issues, let's discuss in #81
